### ISSUE TITLE
Maven repository not available

### ISSUE THREAD

**Issue by dulakm** [bbaumgartner/jtoggl#20]
Hello,

when trying to use your Maven repository (http://pandora.comerge.net:8081/nexus/content/repositories/public_snapshots/) I get "pandora.comerge.net’s server IP address could not be found."

Martin

**Comment by bbaumgartner** [comment]
Hi Martin

Oh yes, this is long gone. Can't you use one of the forks? Usually they are more up-to-date than this branch.

Regards
Benno

**Comment by dulakm** [comment]
Hello Benno,

thanks for the information. I wasn't sure if it is just a temporary issue or the project is abandoned. Now I know. :)

Regards,
Martin

**Comment by ElPsyCongro** [comment]
Can someone tell me if this was in the official maven repositories? Last week I was able to update my project and get the dependency
`<dependency>`
`<groupId>ch.simas.jtoggl</groupId>`
`<artifactId>jtoggl-api</artifactId>`
`<version>1.2.0-SNAPSHOT</version>`
`</dependency>`
but right now I only get a warning that says that it couldn't find the POM of the dependency and it doesn;t get downloaded. Any help?
Does anyone knows where is the latest version of this dependency?
@bbaumgartner @dulakm

**Comment by bbaumgartner** [comment]
Hi Cesar

It is here: https://nexus.comerge.net/#browse/browse:comerge-public-maven:ch%2Fsimas%2Fjtoggl%2Fjtoggl-api%2F1.2.0-SNAPSHOT

Maybe it nexus was just down for maintenance. Please try again. But as said above: This project is pretty death, maybe you want to look into a more up-to-date fork?

Best Regards

**Comment by ElPsyCongro** [comment]
@bbaumgartner Thanks for answering. 
The thing what I need to know is that if the releases of these project where actually on the official maven repositories. Because I were able to download the dependecy by just adding the dependency tag without the repository tag(without that url) that you mention. Then suddenly I couldn't download the dependency anymore.

**Comment by bbaumgartner** [comment]
I did not release it to any other repo. Maybe someone else did.

**Comment by ElPsyCongro** [comment]
I see, well I will test your repo, thanks for your help.
